---
title: O hai der!
email: donchoa@gmail.com
description: |
  O hai der! Im a software developer raised in Montreal, Quebec. Now I live in Toronto and work for Oracle.
baseurl: ''
url: http://charlescy.com
github_username: snwfog
markdown: kramdown
