# Site settings
title: O hai der!
email: donchoa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  O hai der! Im a software developer raised in Montreal, Quebec.
  Now I live in Toronto and work for Oracle.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://charlescy.com" # the base hostname & protocol for your site
github_username: snwfog

# Build settings
markdown: kramdown
